# Can be a spatialdata object or anndata h5ad
data_path = "/path/to/xenium.zarr"
save_path = "/path/to/xenium_spatial_axis.zarr"

# Order of annotations to calculate spatial axis
annotation_order = ["edge", "cortex", "medulla"]
# Either define an annotation column OR broad annotation
# Annotation column should be present in anndata.obs
annotation_column = "lineage" 

k_neighbours = 5

# Column that will be added to anndata.obs
save_column = "spatial_axis"

## Optional
# Allow for processing of experiments independently, 
# that are otherwise in the same data object
batch_id_column = "batch"